'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Activity, AlertTriangle, DatabaseBackup, Film, Loader2, Puzzle, RefreshCw, Server, Settings, Tv } from 'lucide-react';
import { StatusRegion } from '@/components/ui';

interface Report { id: string; status: string; type: string; episode?: { number?: number; anime?: { title?: string } } }
interface Circuit { extensionId: string; state: string }

export default function AdminDashboardPage() {
  const [metrics, setMetrics] = useState<Record<string, any> | null>(null); const [reports, setReports] = useState<Report[]>([]); const [circuits, setCircuits] = useState<Circuit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [metricsResponse, reportsResponse, circuitResponse] = await Promise.all([fetch('/api/admin/metrics'), fetch('/api/reports'), fetch('/api/admin/circuit-breaker')]); const [metricsData, reportsData, circuitData] = await Promise.all([metricsResponse.json(), reportsResponse.json(), circuitResponse.json()]); if (!metricsResponse.ok) throw new Error(metricsData.error || 'Falha ao carregar métricas.'); setMetrics(metricsData); setReports(reportsData.reports || []); setCircuits(circuitData?.data?.extensions || []); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao carregar o painel.'); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  if (loading) return <div className="grid min-h-[55dvh] place-items-center"><StatusRegion className="flex items-center gap-3 text-sm text-[var(--text-secondary)]"><Loader2 className="animate-spin text-[var(--accent)]" />Carregando saúde do sistema…</StatusRegion></div>;
  const kpis = metrics?.kpis || {}; const pending = reports.filter((report) => report.status === 'PENDING');
  const cards = [{ label: 'Animes', value: kpis.animeCount || 0, Icon: Film }, { label: 'Episódios', value: kpis.episodeCount || 0, Icon: Tv }, { label: 'Extensões ativas', value: kpis.enabledExtensionsCount || 0, Icon: Puzzle }, { label: 'Alertas pendentes', value: pending.length, Icon: AlertTriangle }];
  return <div className="mx-auto max-w-7xl space-y-6 p-2 sm:p-6">
    <header className="flex flex-col justify-between gap-4 border-b border-[var(--border-subtle)] pb-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-[var(--accent)]"><Activity size={20} /><span className="text-sm font-semibold">Visão operacional</span></div><h1 className="mt-2 text-2xl font-bold">Saúde do AniStream</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">KPIs, alertas e disponibilidade dos serviços.</p></div><button onClick={() => void load()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-control)] border border-[var(--border-strong)] px-4 text-sm font-semibold"><RefreshCw size={17} />Atualizar</button></header>
    <StatusRegion assertive className="text-sm text-[var(--danger)]">{error}</StatusRegion>
    <section aria-label="Indicadores principais" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(({ label, value, Icon }) => <article key={label} className="surface-panel rounded-[var(--radius-media)] p-4"><div className="flex items-center justify-between text-[var(--text-secondary)]"><span className="text-sm font-medium">{label}</span><Icon size={18} /></div><p className="mt-3 font-mono-data text-3xl font-bold">{value}</p></article>)}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="surface-panel rounded-[var(--radius-media)] p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><Puzzle size={19} className="text-[var(--accent)]" />Extensões Kenjitsu</h2><div className="mt-4 divide-y divide-[var(--border-subtle)]">{circuits.length ? circuits.map((item) => <div key={item.extensionId} className="flex min-h-12 items-center justify-between gap-3 py-2"><span className="text-sm font-semibold">{item.extensionId}</span><span className={`text-sm ${item.state === 'OPEN' ? 'text-[var(--danger)]' : 'text-[var(--success)]'}`}>{item.state === 'OPEN' ? 'Indisponível' : 'Operacional'}</span></div>) : <p className="py-4 text-sm text-[var(--text-muted)]">Nenhum diagnóstico de extensão disponível.</p>}</div></section>
    <section className="surface-panel rounded-[var(--radius-media)] p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><AlertTriangle size={19} className="text-[var(--warning)]" />Atividade recente</h2><div className="mt-4 divide-y divide-[var(--border-subtle)]">{pending.length ? pending.slice(0, 6).map((report) => <div key={report.id} className="py-3"><p className="text-sm font-semibold">{report.episode?.anime?.title || 'Anime'} · Episódio {report.episode?.number || '—'}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{report.type}</p></div>) : <p className="py-4 text-sm text-[var(--text-muted)]">Nenhum alerta pendente.</p>}</div></section></div>
    <nav aria-label="Operações administrativas" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Sistema','/admin/system',Settings],['Comunicados','/admin/broadcasts',Activity],['Backups','/admin/backups',DatabaseBackup],['Integrações','/admin/integrations',Server],['Releases','/admin/releases',RefreshCw]].map(([label, href, Icon]) => { const OperationIcon = Icon as typeof Activity; return <Link key={href as string} href={href as string} className="surface-panel flex min-h-14 items-center gap-3 rounded-[var(--radius-control)] px-4 text-sm font-semibold hover:border-[var(--border-strong)]"><OperationIcon size={18} className="text-[var(--accent)]" />{label as string}</Link>; })}</nav>
  </div>;
}
