import type { PublicExperienceConfig } from '@/types/public-experience';

export const DEFAULT_PUBLIC_EXPERIENCE_CONFIG: PublicExperienceConfig = {
  schemaVersion: 1,
  branding: {
    appName: 'AniStream',
    brandText: 'ANIStream',
    description: 'Catálogo e streaming de animes com Kenjitsu self-hosted.',
    logoLight: '/icon.svg',
    logoDark: '/icon.svg',
    favicon: '/icon.svg',
    showFooter: true,
    showMobileBrand: true,
  },
  theme: {
    preset: 'anistream-dark',
    fontFamily: 'geist',
    density: 'comfortable',
    accent: '#ff6b00',
    accentHover: '#ff8129',
    pageBackground: '#0b0b0f',
    surface: '#111219',
    surfaceElevated: '#181a24',
    textPrimary: '#f8f8fa',
    textSecondary: '#b6b8c4',
    border: '#2d2f3a',
    focus: '#ff9a52',
    success: '#24c78b',
    warning: '#f5aa32',
    danger: '#ef5261',
    radiusControl: 'rounded',
    radiusPanel: 'soft',
  },
  catalog: {
    defaultPageSize: 24,
    columns: { mobile: 2, tablet: 4, desktop: 6 },
    cardDensity: 'comfortable',
    defaultSort: 'popularity',
    showScore: true,
    showYear: true,
    showType: true,
    showStatus: true,
    showEpisodes: true,
    showGenres: false,
    availableFilters: ['search', 'status', 'type', 'genre', 'year', 'score'],
    pageHeadings: {
      catalog: 'Catálogo',
      popular: 'Mais Populares',
      seasons: 'Temporadas',
      movies: 'Filmes',
      search: 'Pesquisar anime',
    },
    placeholderImage: '/icon.svg',
    pinnedAnimeIds: [],
    hiddenAnimeIds: [],
  },
  player: {
    autoplay: false,
    defaultAudio: 'auto',
    defaultSubtitle: 'auto',
    defaultQuality: 'auto',
    defaultSpeed: 1,
    showSourcePicker: true,
    showReport: true,
    keyboardShortcuts: true,
    markCompleted: true,
    skipOpeningSeconds: 0,
    skipEndingSeconds: 0,
    preCacheNextEpisode: false,
    cacheTtlSeconds: 240,
    preferredExtensions: [
      'anikoto',
      'anidb',
      'anibd',
      'animeheaven',
      'animefire',
      'animeplay',
      'animesdrive',
      'animesonlinecc',
      'animesonlinecloud',
      'anitube',
      'dattebayobr',
      'goyabu',
    ],
  },
  features: {
    favorites: true,
    watchHistory: true,
    reports: true,
    pwa: true,
    notifications: true,
    calendar: true,
    advancedPlayer: true,
    search: true,
    seasons: true,
    movies: true,
    releases: true,
    maintenanceBanner: true,
    publicAnnouncements: true,
    changelog: true,
  },
  communication: {
    footerDescription: 'Plataforma moderna de exploração, catálogo e streaming de animes com suporte offline PWA e player avançado.',
    footerCredit: 'Desenvolvido com ♥ para a comunidade otaku.',
    showVersionBadge: true,
    versionLabel: 'Versão 2.2.0',
  },
};

export function publicExperienceThemeVariables(config: PublicExperienceConfig['theme']): Record<string, string> {
  const radiusControl = config.radiusControl === 'sharp' ? '6px' : config.radiusControl === 'pill' ? '999px' : '12px';
  const radiusPanel = config.radiusPanel === 'sharp' ? '8px' : config.radiusPanel === 'soft' ? '16px' : '12px';
  const density = config.density === 'compact' ? '0.9' : config.density === 'airy' ? '1.12' : '1';
  const fontFamily =
    config.fontFamily === 'system'
      ? 'system-ui, sans-serif'
      : config.fontFamily === 'mono'
        ? 'var(--font-geist-mono), monospace'
        : 'var(--font-geist), system-ui, sans-serif';

  return {
    '--background': config.pageBackground,
    '--bg-primary': config.pageBackground,
    '--surface-1': config.surface,
    '--bg-surface': config.surface,
    '--surface-2': config.surfaceElevated,
    '--bg-card': config.surfaceElevated,
    '--text-primary': config.textPrimary,
    '--text-secondary': config.textSecondary,
    '--text-muted': config.textSecondary,
    '--border-subtle': config.border,
    '--border-strong': config.border,
    '--accent': config.accent,
    '--accent-orange': config.accent,
    '--accent-hover': config.accentHover,
    '--accent-orange-hover': config.accentHover,
    '--focus': config.focus,
    '--success': config.success,
    '--warning': config.warning,
    '--danger': config.danger,
    '--radius-control': radiusControl,
    '--radius-panel': radiusPanel,
    '--radius-media': radiusPanel,
    '--public-density': density,
    '--public-font-family': fontFamily,
  };
}
